=== JDamianCabello/Lenguaje-de-marcas/T6/Ejercicios/Ejer4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--Definición de enumeración fuera del elemento-->
  <xs:simpleType name="pagoMes">
    <xs:restriction base="xs:string">
      <xs:enumeration value="mensual"/>
      <xs:enumeration value="semanal"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="Bailes">
    <xs:complexType>
      <xs:sequence>
          <xs:element name="baile">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                  <xs:element name="precio">
                  <xs:complexType mixed="true">
                    <xs:attribute name="cuota" type="xs:pagoMes" use="required"/>
                    <xs:attribute name="moneda" type="xs:string" fixed="euros"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="plazas" type="xs:string"/>
                <xs:element name="comienzo" type="xs:string"/>
                <xs:element name="fin" type="xs:string"/>
                <xs:element name="profesor" type="xs:string"/>
                <xs:element name="sala" type="xs:string"/>
              </xs:sequence>
              <xs:attribute name="id" type="xs:integer" use="required"/>
            </xs:complexType>
          </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JDamianCabello/Lenguaje-de-marcas/T6/Ejercicios/Ejer4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bailes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejer4.xsd">

  <baile id="1">
    <nombre>tango</nombre>
    <precio cuota="mensual" moneda="euro">27</precio>
    <plazas>20</plazas>
    <comienzo>1/1/2011</comienzo>
    <fin>1/2/2011</fin>
    <profesor>Roberto García</profesor>
    <sala>1</sala>
  </baile>

  <baile id="2">
    <nombre>Cha-cha-cha</nombre>
    <precio cuota="trimestral" moneda="euro">80</precio>
    <plazas>18</plazas>
    <comienzo>1/2/2011</comienzo>
    <fin>31/7/2011</fin>
    <profesor>Miriam Gutierrez</profesor>
    <sala>1</sala>
  </baile>
</Bailes>
