=== JDamianCabello/Lenguaje-de-marcas/T6/Ejercicios/Ejer1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cod">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="100"/>
                    <xs:maxInclusive value="10000"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="apellido" minOccurs="1" maxOccurs="2">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                          <xs:minLength value="1"/>
                          <xs:maxLength value="60"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="nombre">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                    <xs:maxLength value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="direccion">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="5"/>
                    <xs:maxLength value="75"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="telefono">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:length value="12"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JDamianCabello/Lenguaje-de-marcas/T6/Ejercicios/Ejer1.xml
<?xml version="1.0" encoding="UTF-8"?>


<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejer1.xsd">

  <alumno>
    <cod>100</cod>
    <apellido>Perez</apellido>
    <apellido>Ortiz</apellido>
    <nombre>Francisco</nombre>
    <direccion>C/ El Palomino</direccion>
    <telefono>+34625412356</telefono>
  </alumno>
  
  <alumno>
    <cod>2000</cod>
    <apellido>Jimenez</apellido>
    <apellido>Sanchez</apellido>
    <nombre>Laura</nombre>
    <direccion>C/ La Palomina</direccion>
    <telefono>+34952623141</telefono>
  </alumno>
  
  <alumno>
    <cod>3000</cod>
    <apellido>Martos</apellido>
    <apellido>Jimenez</apellido>
    <nombre>Vicente</nombre>
    <direccion>C/ B13</direccion>
    <telefono>+34952623143</telefono>
  </alumno>
  
  <alumno>
    <cod>4000</cod>
    <apellido>Ramos</apellido>
    <apellido>Aranda</apellido>
    <nombre>Javier</nombre>
    <direccion>C/ Principal</direccion>
    <telefono>+34952623145</telefono>
  </alumno>
  
  <alumno>
    <cod>10000</cod>
    <apellido>Medina</apellido>
    <apellido>Fernandez</apellido>
    <nombre>Jose</nombre>
    <direccion>C/ Camino del Albero</direccion>
    <telefono>+34952623148</telefono>
  </alumno>
  
</alumnos>
