=== JDamianCabello/Lenguaje-de-marcas/T6/Ejercicios/Ejer2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">


  <xs:element name="libros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="editorial" type="xs:string"/>
              <xs:element name="fechaPublicacion" type="xs:date"/>
              <xs:element name="isbn" type="xs:integer"/>
            </xs:sequence>
            <xs:attribute name="cod" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== JDamianCabello/Lenguaje-de-marcas/T6/Ejercicios/Ejer2.xml
<?xml version="1.0" encoding="UTF-8"?>

<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejer2.xsd">

  <libro cod="1">
    <titulo>El señor de los anillos</titulo>
    <autor>J.R.Tolkien</autor>
    <editorial>La mia</editorial>
    <fechaPublicacion>1994-01-14</fechaPublicacion>
    <isbn>234567890</isbn>
  </libro>
  
    <libro cod="2">
    <titulo>Otro libro</titulo>
    <autor>autor 1</autor>
    <autor>autor 2</autor>
    <editorial>Una editorial</editorial>
    <fechaPublicacion>2000-01-01</fechaPublicacion>
    <isbn>1234567890</isbn>
  </libro>
  


</libros>
