=== JDamianCabello/Lenguaje-de-marcas/T5/Ejemplos/tipoAtributos.dtd
<!ELEMENT xxx (aaa+,bbb+,ccc+,ddd+,eee)>
<!ELEMENT aaa (#PCDATA)>
<!ELEMENT bbb (#PCDATA)>
<!ELEMENT ccc (#PCDATA)>
<!ELEMENT ddd (#PCDATA)>

<!ELEMENT eee (#PCDATA)>

<!ATTLIST aaa valor ID #REQUIRED>
<!ATTLIST bbb id1 ID #REQUIRED>
<!ATTLIST ccc referencia IDREF #REQUIRED>
<!ATTLIST ddd referencia IDREFS #REQUIRED>

<!ATTLIST eee dato CDATA #IMPLIED>

=== JDamianCabello/Lenguaje-de-marcas/T5/Ejemplos/tipoAtributos.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE xxx SYSTEM "tipoAtributos.dtd">
<xxx>
  <aaa valor="a1"></aaa>
  <aaa valor="a2"></aaa>
  <aaa valor="a3"></aaa>
  
  <bbb id1="b001"></bbb>
  <ccc referencia="a3"></ccc>
  
  <ddd referencia="a1 b001 a2"></ddd>
  <eee dato="Hola caracola * € $ %">aa</eee>

</xxx>
