=== JDamianCabello/Lenguaje-de-marcas/T5/Ejercicios/t5Ej5.dtd
<!ELEMENT Bailes (baile+)>
<!ELEMENT baile (nombre, precio, plazas, comienzo, fin, profesor, sala)>
<!ATTLIST baile
          id (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
         cuota (semanal|mensual) #REQUIRED
         moneda CDATA #FIXED "euro">
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT comienzo (#PCDATA)>
<!ELEMENT fin (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT sala (#PCDATA)>

=== JDamianCabello/Lenguaje-de-marcas/T5/Ejercicios/t5Ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bailes SYSTEM "t5Ej5.dtd">

<Bailes>

 <baile id="1">
   <nombre>tango</nombre>
   <precio cuota="mensual" moneda="euro">27</precio>
   <plazas>20</plazas>
   <comienzo>1/1/2011</comienzo>
   <fin>1/2/2011</fin>
   <profesor>Roberto García</profesor>
   <sala>1</sala>
 </baile>
 
 
 <baile id="2">
   <nombre>Cha-cha-cha</nombre>
   <precio cuota="semanal" moneda="euro">80</precio>
   <plazas>18</plazas>
   <comienzo>1/2/2011</comienzo>
   <fin>31/7/2011</fin>
   <profesor>Miriam Gutierrez</profesor>
   <sala>1</sala>
 </baile>
 
</Bailes>
