=== JDamianCabello/Lenguaje-de-marcas/T5/Ejercicios/t5Ej2.dtd
<!ELEMENT ejem_metodo (framework)>
<!ELEMENT framework (versionFramework, clase+)>
<!ELEMENT versionFramework (#PCDATA)>
<!ELEMENT clase (nombre, metodo+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT metodo (ambito, static, tipo_valor_devuelto, nombre_metodo, parametros, codContenido?, comentario?, accion?)>
<!ELEMENT ambito (#PCDATA)>
<!ELEMENT static ANY>
<!ELEMENT tipo_valor_devuelto (#PCDATA)>
<!ELEMENT nombre_metodo (#PCDATA)>
<!ELEMENT parametros (#PCDATA)>
<!ELEMENT accion (#PCDATA)>
<!ELEMENT codContenido (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>

=== JDamianCabello/Lenguaje-de-marcas/T5/Ejercicios/t5Ej2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ejem_metodo SYSTEM "t5Ej2.dtd">
<ejem_metodo>

<framework>
  <versionFramework>NET. Framework 4.5</versionFramework>
    <clase> 
      <nombre>Circulo</nombre>
      <metodo>
        <ambito>public</ambito>
        <static></static>
        <tipo_valor_devuelto>int</tipo_valor_devuelto>
        <nombre_metodo>AreaCirculo</nombre_metodo>
        <parametros>(radio)</parametros>
        <accion>return pi * r^2;</accion>
      </metodo>
    </clase>

    <clase> 
      <nombre>Triangulo</nombre>
      <metodo>
        <ambito>public</ambito>
        <static></static>
        <tipo_valor_devuelto>int</tipo_valor_devuelto>
        <nombre_metodo>AreaTringulo</nombre_metodo>
        <parametros>(base,altura)</parametros>
        <codContenido>return base*altura/2; </codContenido>
        <comentario>Devuelve el area de un triangulo</comentario>
      </metodo>
    </clase>

    <clase>
      <nombre>Cuadrado</nombre>
      <metodo>
        <ambito>public</ambito>
        <static></static>
        <tipo_valor_devuelto>int</tipo_valor_devuelto>
        <nombre_metodo>AreaCuadrado</nombre_metodo>
        <parametros>lado</parametros>
        <codContenido>return lado*lado; </codContenido>
        <comentario>Devuelve el area de un cuadrado</comentario>
      </metodo>
    </clase>
    
</framework>

</ejem_metodo>
